server:
  port: 8080

spring:
  datasource:
    username: hsp
    password: 123456
    url: jdbc:h2:file:./blogDB
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    continue-on-error: true

  h2:
    console:
      enabled: true
      path: /h2
