server:
  port: 8080

spring:
  datasource:
    username: hsp
    password: 123456
    url: jdbc:hsqldb:mem://localhost/blogdb;shutdown=true
    driver-class-name: org.hsqldb.jdbcDriver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    continue-on-error: true

  h2:
    console:
      enabled: true
      path: /h2
